name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/ellipse-1-bg.png
    - assets/page-1/images/ellipse-2-bg.png
    - assets/page-1/images/rectangle-46.png
    - assets/page-1/images/frame-1.png
    - assets/page-1/images/ellipse-1-bg-qGD.png
    - assets/page-1/images/removebg-preview-1.png
    - assets/page-1/images/whatsappimage2023-09-28at856-1.png
    - assets/page-1/images/rectangle-46-izu.png
    - assets/page-1/images/rectangle-46-p4Z.png
    - assets/page-1/images/frame-1-md3.png
    - assets/page-1/images/removebg-preview-1-1.png
    - assets/page-1/images/rectangle-46-wbf.png
    - assets/page-1/images/wavybus-42single-051-removebg-preview-2-1.png
    - assets/page-1/images/wavybus-42single-051-removebg-preview-2-1-8NV.png
    - assets/page-1/images/ellipse-1-bg-6Cq.png
    - assets/page-1/images/email.png
    - assets/page-1/images/rectangle-46-5H3.png
    - assets/page-1/images/email-dUu.png
    - assets/page-1/images/rectangle-46-rc9.png
    - assets/page-1/images/email-XSh.png
    - assets/page-1/images/car.png
    - assets/page-1/images/car-4Ps.png
    - assets/page-1/images/rectangle-46-iP3.png
    - assets/page-1/images/email-eUy.png
    - assets/page-1/images/bike.png
    - assets/page-1/images/rectangle-46-Q49.png
    - assets/page-1/images/rectangle-46-S5w.png
    - assets/page-1/images/f621184568krpx22qcutcqcpxolez4qta0noczckw01-removebg-preview-2.png
    - assets/page-1/images/email-Vxd.png
    - assets/page-1/images/email-iRP.png
    - assets/page-1/images/rectangle-46-VqT.png
    - assets/page-1/images/email-obF.png
    - assets/page-1/images/car-4uo.png
    - assets/page-1/images/parkveu-2-1.png
    - assets/page-1/images/whatsappimage2023-09-28at856-1-byb.png
    - assets/page-1/images/email-6id.png
    - assets/page-1/images/mobile-login-cristina-removebg-preview-1.png
    - assets/page-1/images/rectangle-46-Zqb.png
    - assets/page-1/images/user-sign-icon-front-side-with-white-background-removebg-preview-1.png
    - assets/page-1/images/pic1-1.png
    - assets/page-1/images/frame-1-Job.png
    - assets/page-1/images/menu-icons-40145-1.png
    - assets/page-1/images/menu-icons-40145-1-8JV.png
    - assets/page-1/images/email-pWd.png
    - assets/page-1/images/f621184568krpx22qcutcqcpxolez4qta0noczckw01-removebg-preview-1.png
    - assets/page-1/images/removebg-preview-1-VQm.png
    - assets/page-1/images/rectangle-46-2fb.png
    - assets/page-1/images/rectangle-46-4eu.png
    - assets/page-1/images/rectangle-46-14M.png
    - assets/page-1/images/rectangle-46-Bcu.png
    - assets/page-1/images/rectangle-46-w6H.png
    - assets/page-1/images/rectangle-46-yDK.png
    - assets/page-1/images/removebg-preview-1-uk5.png
    - assets/page-1/images/rectangle-46-LJD.png
    - assets/page-1/images/rectangle-46-FLd.png
    - assets/page-1/images/rectangle-46-CRo.png
    - assets/page-1/images/email-eXs.png
    - assets/page-1/images/email-o9j.png
    - assets/page-1/images/email-PvZ.png
    - assets/page-1/images/email-inM.png
    - assets/page-1/images/email-5AH.png
    - assets/page-1/images/email-yzH.png
    - assets/page-1/images/email-bhT.png
    - assets/page-1/images/email-wMj.png
    - assets/page-1/images/email-ix1.png
    - assets/page-1/images/email-3Db.png
    - assets/page-1/images/bike-UaD.png
    - assets/page-1/images/bike-g1F.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
